# Generated by Django 2.1.2 on 2018-10-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mil_boyutu', models.CharField(max_length=20)),
                ('kece_boyutu', models.CharField(max_length=10)),
                ('pul_boyutu', models.CharField(max_length=10)),
                ('govde_boyut', models.CharField(max_length=20)),
                ('o_ring', models.CharField(max_length=20)),
            ],
        ),
    ]
